### ISSUE TITLE
NPE when parsing MODEL1603150000 from BioModels' non-curated branch

### ISSUE THREAD

**Issue by mglont** [sbmlteam/jsbml#132]
Hi,

Parsing http://www.ebi.ac.uk/biomodels-main/MODEL1603150000 with either 1.2 or a local build of the current master yields a NPE in the parser for the render plugin.

The following unit test

`

    @Test
    public void MODEL1603150000isParsedCorrectly() {
        String path = "/path/to/local/copy/of/model/file";
        try {
            SBMLDocument doc = new SBMLReader().readSBML(path);
            assertNotNull(doc.getModel());
        } catch (Exception e) {
            e.printStackTrace();
            final String msg = new StringBuilder("Cannot parse MODEL1603150000 properly: ").append(
                    e.toString()).toString();
            fail(msg);
        }
    }
`

reproduces the problem, producing the following stacktrace:

> java.lang.NullPointerException
        at org.sbml.jsbml.xml.parsers.RenderParser.processEndDocument(RenderParser.java:403)
        at org.sbml.jsbml.xml.stax.SBMLReader.processEndElement(SBMLReader.java:1262)
        at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:828)
        at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromStream(SBMLReader.java:568)
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:298)
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:280)
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFile(SBMLReader.java:355)
        at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:340)
        at org.sbml.jsbml.SBMLReader.readSBML(SBMLReader.java:215)
        at org.sbml.jsbml.test.TestRenderParser.MODEL1603150000isParsedCorrectly(TestRenderParser.java:19)

**Comment by mglont** [comment]
The model is valid based on the following settings for the online validator:   
- Units consistency checking: off
- Identifier consistency checking: on
- MathML consistency checking: on
- SBO consistency checking: on
- Overdetermined model checking: on
- Modeling practices checking: on
- Overall SBML consistency checking: on
- Ignore SBML Level 3 packages that are not officially finalized: off

**Comment by niko-rodrigue** [comment]
ok, I can reproduce the problem. The model contain the render namespace declaration at the top of the model but there are no elements defined in this namespace in the model. Some part of the render parser where expecting some elements, I will try to fix this.

Thanks
Nico

**Comment by niko-rodrigue** [comment]
The issue should be fixed now.
