### ISSUE TITLE
Notes format

### ISSUE THREAD

**Issue by tpfau** [sbmlteam/jsbml#140]
I'm currently trying to figure out how best to encode Notes when calling jsbml from matlab. 
I used to do something like this
```Matlab
notesString = '<body xmlns=\"http://www.w3.org/1999/xhtml\">';
notesString = [notesString, some_note_data_in_html];
notesString = [notesString, '</body>'];
```
However, this seems not to work with and yields an error:
```
javax.xml.stream.XMLStreamException: Trying to redeclare prefix xml from
its default URI http://www.w3.org/XML/1998/namespace to "http://www.w3.org/1999/xhtml"
    at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1473)
    at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1480)
    at com.ctc.wstx.sw.BaseNsStreamWriter.setPrefix(BaseNsStreamWriter.java:186)
    at com.ctc.wstx.sw.SimpleNsStreamWriter.writeNamespace(SimpleNsStreamWriter.java:144)
    at org.sbml.jsbml.xml.parsers.XMLNodeWriter.write(XMLNodeWriter.java:160)
    at org.sbml.jsbml.xml.parsers.XMLNodeWriter.write(XMLNodeWriter.java:210)
    at org.sbml.jsbml.xml.parsers.XMLNodeWriter.write(XMLNodeWriter.java:115)
    at org.sbml.jsbml.xml.stax.SBMLWriter.writeNotes(SBMLWriter.java:909)
    at org.sbml.jsbml.xml.stax.SBMLWriter.writeSBMLElements(SBMLWriter.java:1082)
    at org.sbml.jsbml.xml.stax.SBMLWriter.writeSBMLElements(SBMLWriter.java:1135)
    at org.sbml.jsbml.xml.stax.SBMLWriter.writeSBMLElements(SBMLWriter.java:1135)
    at org.sbml.jsbml.xml.stax.SBMLWriter.write(SBMLWriter.java:642)
    at org.sbml.jsbml.xml.stax.SBMLWriter.write(SBMLWriter.java:487)
    at org.sbml.jsbml.SBMLWriter.write(SBMLWriter.java:657)
```
It works if I explicitly declare the html namespace in the SBMLDocument and use <html:p> as tags on the notes, but I'm wondering, whats wrong with the other version.

**Comment by niko-rodrigue** [comment]
There is a mess up with the XML libraries as matlab include many old versions of those that are put at the start of the classpath. I am hoping to be able to solve this problem by using proguard (https://www.guardsquare.com/en/proguard) to change the packages of the XML libraries we use in JSBML to try to prevent some of those libraries clash but I had no time to try it out yet.
