### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil

### ISSUE THREAD

**Issue by lcottret** [sbmlteam/jsbml#235]
Hi,

Version of JSBML : 1.6-SNAPSHOT (maven).

When I write a SBML file, this exception now occurs : 
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:253)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:265)
	at org.biojava.nbio.ontology.OntoTools.<clinit>(OntoTools.java:37)
	at org.biojava.nbio.ontology.io.OboParser.parseOBO(OboParser.java:84)
	at org.sbml.jsbml.SBO.<clinit>(SBO.java:231)
	at org.sbml.jsbml.AbstractSBase.setSBOTerm(AbstractSBase.java:2828)

Regards,
Ludo

**Comment by niko-rodrigue** [comment]
Could you try it again ? I have changed the dependencies in maven and the jar included in github and it should be working again. I have updated the 1.6-SNAPSHOT on maven yesterday.

**Comment by mhucka** [comment]
Hi Nico,

Thank you for doing this (on Dec. 24, no less!)

MH

**Comment by lcottret** [comment]
Thanks  @niko-rodrigue, it works !
